<template>
  <q-dialog persistent v-model="showPopup" v-if="showPopup" @hide="showPopup=false" :position="isMobile ? 'bottom' : 'standard'">
    <q-card class="bg-grey-2">
      <q-card-section>
        <div class="row justify-center">
          <div class="col-auto text-primary">
            <q-icon size="xl" name="mdi-certificate" color="primary"/>
          </div>
        </div>
        <div class="row justify-center q-pt-xs">
          <div class="col-auto items-center">
            <div class="text-primary text-bold text-center" :class="isMobile ? 'text-h6' : 'text-h5'">
              <span class="vertical-middle">RTL self signed SSL certificate</span>
            </div>
            <div class="text-primary text-left text-subtitle2 q-pt-xs">
              <b>Your connection to RTL is secure. </b> Your browser may alert you that SSL certificate is unknown.
              RTL is protected with TLS certificate generated by LND which is self signed certificate (not recognized by browser).
            </div>
          </div>
        </div>
      </q-card-section>
      <q-card-actions align="center" class="text-primary">
        <q-btn glossy @click="close()" color="primary" text-color="white">I UNDERSTAND</q-btn>
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

<style>
</style>

<script lang="ts">

import GlobalMixin from 'src/mixins/global-mixin';
import { get } from 'src/api/http-service';
import { showNotificationError } from 'src/api/notificatios-api';
import Loader from 'components/utils/Loader.vue';
import { decryptSymmetricCtr } from 'src/api/encryption-service';

export default GlobalMixin.extend({
  name: 'RtlInsecurePopup',
  components: { Loader },
  props: {
    show: {
      type: Boolean,
      required: true,
    },
    rtlAddress: {
      type: String,
      required: false,
      default: '',
    },
  },
  data() {
    return {
      showPopup: false,
      showLoading: false,
      userBtcWalletDto: null,
      showConfirmMasterPasswordPopup: false,
      lnWalletSeed: null,
      showSeedPopup: false,
    };
  },
  watch: {
    show() {
      this.showPopup = true;
    },
  },
  methods: {
    async onPasswordConfirmed(password: string) {
      get(this.$axios, '/api/lnd/seed', (res: any) => {
        this.showSeedPopup = !this.showSeedPopup;
        // @ts-ignore
        this.lnWalletSeed = decryptSymmetricCtr(res.data.encryptedArtefact, password);
      }, (err: any) => {
        showNotificationError('Getting LN node wallet seed failed', 'Unexpected error occurred');
        console.log(err);
      });
    },
    close() {
      this.openUrlNewTab(this.rtlAddress);
      this.showPopup = false;
    },
  },
});
</script>
